### ISSUE TITLE
Look at using JSCS as a style checker

### ISSUE THREAD

**Issue by thisandagain** [MozillaFoundation/mofo-example-app#10]
Have folks looked at JSCS? It doesn't have a python dependency and has an "AirBNB" preset built-in that is maintained by the community:

https://github.com/jscs-dev/node-jscs
https://github.com/jscs-dev/node-jscs/blob/master/presets/airbnb.json

**Comment by thisandagain** [comment]
Using for `build.webmaker.org` repo to enforce the AirBnb style guide. Works fairly well: https://github.com/mozilla/build.webmaker.org/blob/master/.jscsrc

**Comment by gvn** [comment]
The more I look into JSCS the more I want to use it. Seems really nice.

**Comment by Pomax** [comment]
nice. if it's easy to set up, let's put it in and see how it holds up, even if we switch to another thing after more evaluation.

**Comment by Pomax** [comment]
added~~
