### ISSUE TITLE
Look for best solution or different way to localize React app

### ISSUE THREAD

**Issue by alicoding** [MozillaFoundation/mofo-example-app#13]
We need to figure out how to localize React app and what is the best practice here.

One suggestion was using https://github.com/yahoo/react-intl, but we could also use our in-house l10n library and modify it to support React syntax which proves by @pomax that it will work.

I'm creating this bug for discussion and also implementation on the example app.

**Comment by Pomax** [comment]
there is no reason not to use both. react-intl offer things we can't currently localise all that well, like dates.

**Comment by alicoding** [comment]
So I guess we could look into momentjs and yahoo 's library too

**Comment by jbuck** [comment]
I am always in favour of using code that someone else maintains if it suits our needs. Honestly, I'd just try translating with the yahoo lib and see how it works. If it's good enough, lets use it.

**Comment by Pomax** [comment]
dicussing with @alicoding:

- pure client-side apps are going to have problems because they don't support navigator.language/languages

**Comment by Pomax** [comment]
## dev plan
- [ ] settle on which libraries to try to use (the less code we write, the better)
- [ ] implement minimal viable localisation in the gallery app
- [ ] figure out where things break down based on that

**Comment by jbuck** [comment]
I might have a sol'n for the accept-language header and navigator.languages: https://bugzilla.mozilla.org/show_bug.cgi?id=1113376

**Comment by alicoding** [comment]
So, I was thinking of couple of things here.

First is to stick with Yahoo React-intl library which I think `27K` might not be too **big** but that's an option anyway. Second option here is to create our in-house l10n library which I have started and will do more since we have done lots of work for [node-webmaker-i18n](http://github.com/mozilla/node-webmaker-i18n) and can port most of its functionality, but only one I want to improve a lot is the `gettext` which ideally I want it to work the same way as **clang gettext**. I know it might be a lot of work, but this way we will know exactly what we need.

Thoughts @Pomax @simonwex @jbuck

**Comment by davidascher** [comment]
Two thoughts @alicoding:

a) let's blog the problem, and invite comments from people who have been down similar paths before.

b) Just FYI, 1.1 came out today: https://github.com/yahoo/react-intl/releases/tag/v1.1.0

**Comment by alicoding** [comment]
I think this can be closed since we have a solution to React app. We are using React-Intl and some of the example can be found here http://github.com/mozilla/donate.mozilla.org we have documented these really well in the repo.
