### ISSUE TITLE
Let's negotiate the directory structure

### ISSUE THREAD

**Issue by davidascher** [MozillaFoundation/mofo-example-app#14]
First, let's avoid spaces in dirnames. They have a tendency to mess up unix command line invocations, and are definitely unusual.

I'm not convinced separating jsx code in a directory makes more sense than simply having jsx files be identified by the toolchain based on their extensions.  

In general, the directory structure feels not-there-yet:

* Having two apps in a single repo I think makes the structure more complex than needed, and I'm not sure we would have multiple apps per repo in general.  I guess I'm wondering whether that complexity is one we want to carry in every repo that people fork from this repo.
  
* the code in `/apps` corresponds to the server side stuff but also has client-side assets, which would be fine except the critical client-side code is the `react code` dir.  When coding, I find that I want all client-side stuff (including images, html, and less/css to be near to the app logic.  It's clearly disturbing me to have `react code` on one side, and client side stuff nested in `public/` inside of the apps.  Then again, maybe you're thinking that we'll have react code run on both client & server.

**Comment by k88hudson** [comment]
+1

**Comment by Pomax** [comment]
The only reason the apps exist in the same repo is because I needed a running example. Can't easily run multiple apps on different ports without the CORS headache so I'm on board for making them different repos, we just need to spend some more time getting CORS working properly before that can happen.

We can place the .jsx files "anywhere", my thought is not so much running it on both server and client, but "these are build files". The actual .js code is generated off of them in the same way that the .css files are generated off of .less files, and it feels weird to put data used in the build in the user facing directories. My idea was to separate build and deploy data, because they aren't used client-side at all.

**Comment by davidascher** [comment]
I understand.  FYI, what I did (stealing from someone else's template) in https://github.com/davidascher/plzkthx is to have all the 'source' files (that people edit) in an `app` directory.  The gulp task in that setup does bundling in a 'build' directory (and serves those files updating watchify for the dev edit-refresh cycle).  There's a separate task for 'deploy' which does aggressive minimization in a `deploy` directory.

I agree we don't want to mix built files with source files.  I think I just want source files near each other.

**Comment by Pomax** [comment]
that makes sense; I'd like to still split up sources in terms of their roles, would a source structure like
```
app
├ components (jsx files)
├ mixins (genuine mixins)
├ lib (general JS)
├ less (err.. less)
└┄
```
make sense to you? That way all the source data is in a logical place, but we still have a clean separation for build tools, as well as keeping it obvious where the various parts go.

**Comment by davidascher** [comment]
+1

plain old HTML and image files should live in subdirs of `app` as well,
right?

**Comment by Pomax** [comment]
probably, although it feels like things that "just work" in the browser probably belong in their own dir, like ye olde "public_html" but then with fewer underscores?
```
app
├ components (jsx files)
├ mixins (genuine mixins)
├ lib (general JS)
├ less (err.. less)
├┄
└public
 ├ images
 ├ css
 └  ┄
```
maybe?

**Comment by davidascher** [comment]
`public` wfm

aside: what do you mean by 'genuine mixins'?

**Comment by Pomax** [comment]
Genuine mixins, following the React mixin formula with life cycle function hooking, as opposed to helpful JavaScript we write as additional functionality for use inside components. Ideally that JS is written as a standalone thing and then installed using npm/bower/jspm/... anyway, but I want to make sure we agree to not put "general JS" in the mixin dir

**Comment by davidascher** [comment]
makes sense
