### ISSUE TITLE
Clarify the steps needed to get a really fast edit/refresh cycle

### ISSUE THREAD

**Issue by davidascher** [MozillaFoundation/mofo-example-app#16]
Developer productivity is enhanced by minimizing the time and steps needed between saving a file and seeing the result.  Let's make sure we use best-of-breed tooling to help that.

Things I've used in that category include `live-server` for serving static assets, `watchify` as part of the browserify tool chain, and `live-reload`, although the last one tends to do poorly in Firefox in my (not extensive) experience.

**Comment by Pomax** [comment]
+1, although we first need to actually finish figuring out what our build system *is* before we can document how to work with it efficiently =)

**Comment by davidascher** [comment]
Fair enough!  Feel free to tweak the issue title =)

**Comment by davidascher** [comment]
For institutional memory: Had some good success with https://github.com/schmich/connect-browser-sync in the past, even though browser-sync has  a much more general use case in mind.

**Comment by Pomax** [comment]
research data - based on https://gist.github.com/substack/68f8d502be42d5cd4942 it sounds like browserify offers more freedom in build setup than webpack does. I was considering webpack for it "hot module reload" capabilities here, but will be searching on to see if that can be done easily outside of webpack, too.

**Comment by Pomax** [comment]
I'm actually treating this issue as "solved" now that `gulp watch` fires up all the live-servers necessary to automate the live development cycle.
