### ISSUE TITLE
When a less file is changed, there is no live-reload

### ISSUE THREAD

**Issue by davidascher** [MozillaFoundation/mofo-example-app#36]
Something's not quite right in the gulp-watch dependency chain.

**Comment by Pomax** [comment]
That's odd, the only time I see live-reload not doing something is when the less compile errors out (at which point `gulp watch` dies). Do you see any errors, or is this for legal LESS changes, too?

**Comment by simonwex** [comment]
@davidascher repeatable?

**Comment by davidascher** [comment]
closing. will reopen if it hits me again
