### ISSUE TITLE
Work out how to best instrument metrics using React, and add to example app

### ISSUE THREAD

**Issue by simonwex** [MozillaFoundation/mofo-example-app#40]
Adding instrumentation and metrics to our apps is something we need to get better at. A good start would be to make it easier to do. 

@adamlofting any thoughts you have here would be a useful start.

**Comment by adamlofting** [comment]
:+1: I'll make this a priority this :heartbeat: 

See also: Let's talk routing and metrics #35

**Comment by adamlofting** [comment]
Notes:
- [ ] Basic GA (Universal Analytics version)
  - [ ] Check how this works with react routing
- [ ] Config for staging and prod versions
- [ ] webmaker-analytics module? (worth making more generic than webmaker?)
  - [ ] Check how this works with react
- [ ] example event tracking (in app or in handbook)
- [ ] Optimizely by default? Maybe option to switch on with a config
  - [ ] Check out this works with react
- [ ] New Relic?

**Comment by adamlofting** [comment]
I've opened a PR to talk this through as it takes shape:
https://github.com/MozillaFoundation/mofo-example-app/pull/48

**Comment by adamlofting** [comment]
Basic GA could do with environment variables, and some templating options: https://github.com/MozillaFoundation/mofo-example-app/issues/51

**Comment by adamlofting** [comment]
There might be some magic we can work with in here:
https://github.com/facebook/react/blob/2aeb8a2a6beb00617a4217f7f8284924fa2ad819/src/browser/eventPlugins/AnalyticsEventPluginFactory.js

**Comment by adamlofting** [comment]
Fixed in #48
