### ISSUE TITLE
Generic React Metrics Module / Mixin / Thing

### ISSUE THREAD

**Issue by adamlofting** [MozillaFoundation/mofo-example-app#53]
I plan to write a generic React Metrics (Google Analytics) Module that works in place of:

1. The [event tracking currently in example-app](https://github.com/MozillaFoundation/mofo-example-app/commit/767c54b4bbb9f7f53829e36475ced39bf77e9752). 
2. The [pageview tracking currently in the teach site](https://github.com/mozilla/teach.webmaker.org/commit/c7ee3eccbb27941a448637b25925618b6c6eaacf)

**Comment by adamlofting** [comment]
#35

**Comment by toolness** [comment]
Nice!

I actually refactored your pageview tracking in the teach site in https://github.com/mozilla/teach.webmaker.org/commit/bd0a8b3b15276d31615e57f0f4501a790790e168... Curious to know your thoughts on that--sorry I didn't submit it as a formal PR!

**Comment by adamlofting** [comment]
I started moving the code from teach into a module today. Plenty of work still to do on this, but the code is here: https://github.com/adamlofting/react-ga

**Comment by toolness** [comment]
:+1:

**Comment by Pomax** [comment]
nice!

**Comment by adamlofting** [comment]
This should be closed with https://github.com/MozillaFoundation/mofo-example-app/pull/56 once it's been reviewed.

**Comment by adamlofting** [comment]
[react-ga](https://github.com/adamlofting/react-ga) is the 'generic module thing' this ticket called for.
